[tool.poetry]
name = "flashing_nozzle_design"
version = "0.0.1"
description = "Sizing and analysis tools for flashing nozzles and turbines."
authors = ["Roberto Agromayor <roagr@dtu.dk>", "Simone Parisi <sipar@dtu.dk>", "Fredrik Haglind <fhag@dtu.dk>"]
license = "MIT"
readme = "README.md"
keywords = ["flashing-flow", "two-phase-flow", "nozzle-design", "organic-rankine-cycle", "turbomachinery"]
package-mode = true
packages = [{ include = "flashing_nozzle_design", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
jaxprop = "0.5.6"

[tool.poetry.group.dev.dependencies]
ipython = "^8.24.0"
black = "^24.4.2"
pytest = "^8.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
